### ISSUE TITLE
Notice messaging is misleading

### ISSUE THREAD

**Issue by jasonbahl** [Appsero/client#30] opened 2023-04-10 19:01 UTC
The wording that is output in the admin notice is maybe a bit misleading. 

The notice states that "Site name and Url, your name and email address" are collected. Then immediately states "No sensitive data is tracked". 

![Screen Shot 2023-04-07 at 1 59 09 PM](https://user-images.githubusercontent.com/1260765/230973584-20e9b950-015e-455c-a2c2-3ffa64b5da49.png)

I've had users argue that "name and email" are sensitive data and that the messaging here is misleading.

**Comment by Hakira-Shymuy** [comment] 2023-08-09 11:31
> Thanks @jasonbahl. Seems like it. We'll do a fix of this in the next release of of Client SDK

for when those fixes in the 2 issues that are opened on github?
your answers was in April, we are in August

**Comment by anisAronno** [comment] 2023-08-10 09:59
Thanks @jasonbahl.  Appreciate your patience. The issue is now fixed in the latest release.

**Closed by anisAronno** 2023-08-10 09:59 UTC
